language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '14'

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - aduartem@miumg.edu.gt
      - alan@warava.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: 'Project deployed'
  on:
    branch: master