language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '14'

git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  skip-cliean: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Project deployed'
  on:
    branch: master